# required properties
group = com.almostreliable
modId = almostunified_ie
modName = Almost Unified Immersive Engineering
modVersion = 1.0.0
minecraftVersion = 1.21.1
neoforgeVersion = 21.1.164

# replacement properties
modAuthor = Almost Reliable
modDescription = Almost Unified integration for Immersive Engineering.
license = All Rights Reserved
githubUser = AlmostReliable
githubRepo = almostunified_ie

# mod dependencies
auVersion = 1.2.7
ieVersion = 12.4.2-194

# settings
neoForge.parchment.minecraftVersion = 1.21.1
neoForge.parchment.mappingsVersion = 2024.11.17
almostgradle.buildconfig.name = ModConstants
almostgradle.launchArgs.autoWorldJoin = true
almostgradle.recipeViewers.jei.runConfig = true
almostgradle.recipeViewers.jei.version = 19.21.0.246

# gradle
org.gradle.vfs.watch = true
org.gradle.configuration-cache = true
org.gradle.parallel = true
